In [ ]:
### Insertando código Python

In [10]:
x = 10
y = 15
prom = (x+y)/2
print (prom)

12.5


In [23]:
### Trabajando con listas
A = [5.2,5.8,5.9]
## Recordemos funciones para trabajar listas
print(type(A))
print(len(A))
print(A)
A.append(10.9)
A.clear()
print(A)
print(len(A))
A = [5.2,5.8,5.9,15.6,8.975]
A.count(5.2)
B=A.copy()
print(A)
print(B)
print(id(B))
print(id(A))
C=[2,3,6]
A.extend(C)
print(id(A))
id(5)


<class 'list'>
3
[5.2, 5.8, 5.9]
[]
0
[5.2, 5.8, 5.9, 15.6, 8.975]
[5.2, 5.8, 5.9, 15.6, 8.975]
140560562781192
140560562781448
140560562781448


10914624

In [35]:
A = [5.2,5.8,5.9,15.6,8.975]
print(A.index(15.6))
A.index(5.2)
A.insert(3,10)
A.pop()
A.remove(10)
print(A)
A.reverse()
print(A)
A.sort()
A


3
[5.2, 5.8, 5.9, 15.6]
[15.6, 5.9, 5.8, 5.2]


[5.2, 5.8, 5.9, 15.6]

In [2]:
print(id(5))
print(id(10))
A=[5,10]
print(id(A))
print(A[0])
print(A[1])
print(id(A[0]))
print(id(A[1]))                                                                        

140718025291680
140718025291840
1865373828992
5
10
140718025291680
140718025291840


In [3]:
print(A)
## i  es un elemento de la lista
s = 0
for i in A:
    s = s+ i                               
print(s)    

[5, 10]
15


In [4]:
## i es el index de la lista

S=0
for i in range(len(A)):
  S = S + A[i]
print(S)

type(A)
A.extend(["hola"])
A

15


[5, 10, 'hola']

In [5]:
type(A)
A.extend(["hola"])
A

[5, 10, 'hola', 'hola']

In [7]:
###importando librerías:
import numpy as np

A = [5.2,5.8,5.9]
Ar = np.array(A)
print(Ar)
sum(Ar)
media = np.mean(Ar)
print(media)
varianza = np.var(Ar)
print(varianza)
B = np.array([[1, 2, 3], [4, 5, 6]])
print(B)
print(np.mean(B[0]))
print(np.mean(B,axis=1))
print(np.mean(B,axis=0))
print(B.mean(axis=1))
print(B.mean(axis=0))
print(B[:,0].mean())                        

[5.2 5.8 5.9]
5.633333333333333
0.09555555555555555
[[1 2 3]
 [4 5 6]]
2.0
[2. 5.]
[2.5 3.5 4.5]
[2. 5.]
[2.5 3.5 4.5]
2.5


In [47]:
###importando librerías:
import numpy as np
Ar = np.array(A)
print(Ar)
type(Ar)

['5.2' '5.8' '5.9' '15.6' 'h' 'o' 'l' 'a' 'hola']


numpy.ndarray

In [10]:
! pip install pandas
import pandas

In [16]:
!echo "hola mundo"
!mkdir PRUEBA
!dir
!ver
!path
!cd

"hola mundo"


Ya existe el subdirectorio o el archivo PRUEBA.


 El volumen de la unidad C no tiene etiqueta.
 El n£mero de serie del volumen es: 3C5D-197B

 Directorio de C:\Users\ANA\Desktop

17/01/2021  22:36    <DIR>          .
17/01/2021  22:36    <DIR>          ..
13/01/2021  10:37    <DIR>          .ipynb_checkpoints
28/12/2019  06:27             8,440 .RData
02/12/2020  21:33             2,018 .Rhistory
15/01/2021  23:45    <DIR>          ACRE
14/01/2021  15:33             3,416 APUNTES.txt
02/05/2020  13:53    <DIR>          BooksTesisJaime
14/01/2021  11:04    <DIR>          clases
11/01/2021  06:41               150 crede.txt
24/11/2020  13:08    <DIR>          CURSOS
21/06/2020  17:00             1,303 Dropbox.lnk
10/11/2020  07:16    <DIR>          EdxIntroductionComputerSciencewith Pytohn
17/08/2020  10:59    <DIR>          English
28/09/2018  01:55             7,490 Eula.txt
13/10/2018  20:14             2,483 Excel 2016.lnk
21/12/2020  18:55    <DIR>          fotos
20/11/2020  19:12             2,345 GitHub Desktop.lnk
07/07/2019  1

In [8]:
print(A)


[5.2, 5.8, 5.9]
